services:
  - type: web
    name: buddyread
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_BOOKS_KEY
        sync: false
